//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMka.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int IdApplication { get; set; }
        public string NameApp { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<System.DateTime> DateCompletion { get; set; }
        public string Descroption { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public string Atrubute { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
